# Generated by Django 4.2 on 2023-04-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_description_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'managed': True, 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='Brand',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
