# Generated by Django 4.2 on 2023-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_product_quantity_alter_product_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
